=== Geipman/faktura/docs/migration/schema/tblAnlieferungOrt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblAnlieferungOrt" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblAnlieferungOrt">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAB7TfaI7L7VEb2gCAA2oCMDAAAAACCgD74MJ+JAAAAAAAAAAABBAG4A
bABpAGUAZgBlAHIAdQBuAGcAcwBPAHIAdAAAAAAAAAB8TfaI7L7VEb2gCAA2oCMD
BwAAAHtN9ojsvtURvaAIADagIwNBAG4AbABpAGUAZgBlAHIAdQBuAGcAcwBPAHIA
dAAAAA==
"/>
<od:tableProperty name="GUID" type="9" value="e032iOy+1RG9oAgANqAjAw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="AnlieferungsOrt" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1608"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="fE32iOy+1RG9oAgANqAjAw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Geipman/faktura/docs/migration/data/tblAnlieferungOrt.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblAnlieferungOrt.xsd" generated="2026-07-15T21:21:51">
<tblAnlieferungOrt>
<AnlieferungsOrt>Biebesheim</AnlieferungsOrt>
</tblAnlieferungOrt>
<tblAnlieferungOrt>
<AnlieferungsOrt>Geinsheim</AnlieferungsOrt>
</tblAnlieferungOrt>
<tblAnlieferungOrt>
<AnlieferungsOrt>Gernsheim</AnlieferungsOrt>
</tblAnlieferungOrt>
<tblAnlieferungOrt>
<AnlieferungsOrt>Stockstadt</AnlieferungsOrt>
</tblAnlieferungOrt>
<tblAnlieferungOrt>
<AnlieferungsOrt>Friedhof</AnlieferungsOrt>
</tblAnlieferungOrt>
<tblAnlieferungOrt>
<AnlieferungsOrt>Griesheim</AnlieferungsOrt>
</tblAnlieferungOrt>
<tblAnlieferungOrt>
<AnlieferungsOrt>Riedstadt</AnlieferungsOrt>
</tblAnlieferungOrt>
</dataroot>
