=== Geipman/faktura/docs/migration/schema/tblMaterialarten.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblMaterialarten" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblMaterialarten">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Material " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAB8GuVyL/H0T75rdQI3C2Q2AAAAAD/QvJczRuNAAAAAAAAAAAB0AGIA
bABNAGEAdABlAHIAaQBhAGwAYQByAHQAZQBuAAAAAAAAALijQQ9pRslDvG8u3whD
gw4HAAAAfBrlci/x9E++a3UCNwtkNk0AYQB0AGUAcgBpAGEAbAAAAAAAAADlwobe
CRFnTZKfNY4mA2aWBwAAAHwa5XIv8fRPvmt1AjcLZDZOAGUAdAB0AG8AcAByAGUA
aQBzAAAAAAAAAOqaiTS7VgNHlIuY6F5LIvYHAAAAfBrlci/x9E++a3UCNwtkNk0A
dwBzAHQAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="xHoBxkBr3EObuoLVFGb1Ww==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Material" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="7335"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Nettopreis" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1620"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="#,##0.00 €;-#,##0.00 €"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Mwst" minOccurs="0" od:jetType="decimal" od:sqlSType="decimal">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Percent"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:decimal">
<xsd:totalDigits value="4"/>
<xsd:fractionDigits value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Einheit" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Geipman/faktura/docs/migration/data/tblMaterialarten.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblMaterialarten.xsd" generated="2026-07-15T21:21:21">
<tblMaterialarten>
<Material>Abfälle (AS 20 03 01)</Material>
<Nettopreis>85</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abfälle aus der Holzbearbeitung (AS 03 01 05)</Material>
<Nettopreis>100</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abfälle aus pflanzlichem Gewebe (AS 02 01 03)</Material>
<Nettopreis>15</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abgabe Bau- und Abbruchabfälle (AS 17 09 04)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abgabe Leichtstoffe (AS 19 05 01)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abgabe Mineralische Abfälle (AS 19 12 09)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abgabe Mischschrott (AS 17 04 05)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abgabe Siebüberlauf (AS 19 05 01)</Material>
<Nettopreis>5</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Abgabe Siedlungsabfälle (AS 20 03 01)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>AdBlue</Material>
<Nettopreis>0.45</Nettopreis>
<Mwst>0.19</Mwst>
</tblMaterialarten>
<tblMaterialarten>
<Material>Anfahrt Schredder und Ladefahrzeug (pauschal)</Material>
<Nettopreis>220</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Anzahlung</Material>
<Nettopreis>1</Nettopreis>
<Mwst>0</Mwst>
</tblMaterialarten>
<tblMaterialarten>
<Material>Aufbereitete holzige Biomasse Qualität A [m³]</Material>
<Nettopreis>20</Nettopreis>
<Mwst>0.07</Mwst>
<Einheit>m³</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Aufbereitete holzige Biomasse Qualität B [m³]</Material>
<Nettopreis>20</Nettopreis>
<Mwst>0.07</Mwst>
<Einheit>m³</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Aufbereitung biogener Reststoffe</Material>
<Nettopreis>40</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Bauschutt gemischt (AS 17 01 07)</Material>
<Nettopreis>25</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Betreuung Grünsammelstelle (Monatspauschale)</Material>
<Nettopreis>200</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Betrieb eines Radladers mit Fahrer</Material>
<Nettopreis>75</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Std</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Big Bag - Abfüllung</Material>
<Nettopreis>25</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>BigBag</Material>
<Nettopreis>8</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Küchen- und Kantinenabfälle (AS 20 01 08)</Material>
<Nettopreis>35</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Bioabfall aus kommunaler Sammlung (AS 20 03 01)</Material>
<Nettopreis>45</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Bioabfall verunreinigt (AS 20 03 01)</Material>
<Nettopreis>39</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Bioabfall vorbehandelt (AS 20 03 01)</Material>
<Nettopreis>20</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Bioabfalltüten (Karton à 300 Stück)</Material>
<Nettopreis>15</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Bioabfalltüten (Pack à 25 Stück)</Material>
<Nettopreis>1.68</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Biofiltermaterial (AS 02 01 03)</Material>
<Nettopreis>5</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Biologisch abbaubare Abfälle (AS 20 02 01)</Material>
<Nettopreis>45</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Biomasse aufbereitet</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Biomasse aufbereitet [m³]</Material>
<Nettopreis>15</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>m³</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Biomasse zur Aufbereitung [t]</Material>
<Nettopreis>4.5</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Biomasse zwischenlagern (pauschal)</Material>
<Nettopreis>30</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Blumenerde</Material>
<Nettopreis>46.22</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>m³</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Dachsubstrat (AS 20 02 02)</Material>
<Nettopreis>35</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Einsatz eines Spritzwagens mit Traktor und Fahrer</Material>
<Nettopreis>75</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Std</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Einsatz Radlader inkl. aller Kosten (pro Std.)</Material>
<Nettopreis>60</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Std</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Einsatz Schredder inkl. aller Kosten (pro Std.)</Material>
<Nettopreis>140</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Std</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Erdaushub (AS 20 02 02)</Material>
<Nettopreis>25</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Erdaushub (SONDERPREIS)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Erdaushub mG (SONDERPREIS)</Material>
<Nettopreis>1</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Erdaushub mit Grünschnitt, Wurzeln (AS 20 02 02)</Material>
<Nettopreis>30</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Fallschutzbelag natur 5/30</Material>
<Nettopreis>30</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>m³</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Feinkompost 0/12</Material>
<Nettopreis>11.21</Nettopreis>
<Mwst>0.07</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Feinkompost 0/12 (Grüngut)</Material>
<Nettopreis>16</Nettopreis>
<Mwst>0.07</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Feinkompost 0/12 (Grüngut) Sonderpreis</Material>
<Nettopreis>10</Nettopreis>
<Mwst>0.07</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Flyer &quot;Was gehört in die Biotonne?&quot;</Material>
<Nettopreis>0.02</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Forstabfälle (AS 02 01 07)</Material>
<Nettopreis>15</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Fremdwägung</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
</tblMaterialarten>
<tblMaterialarten>
<Material>Fremdwägung (Schottertragschicht 0/32 - Naturmaterial)</Material>
<Nettopreis>0</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Friedhofabfälle (AS 20 02 01)</Material>
<Nettopreis>22.5</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Frischkompost</Material>
<Nettopreis>5</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Gemüseabfälle (AS 02 03 04)</Material>
<Nettopreis>15</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Getreideabfälle (AS 02 03 04)</Material>
<Nettopreis>15</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Gewebesack</Material>
<Nettopreis>0.84</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>Stk</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Grünabfall (AS 20 02 01)</Material>
<Nettopreis>35</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Grünabfall (AS 20 02 01) [m³]</Material>
<Nettopreis>7.5</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>m³</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Grünabfall inkl. Transport (AS 20 02 01)</Material>
<Nettopreis>33</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Grünabfall mit Fremdstoffen (AS 20 02 01)</Material>
<Nettopreis>29</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
<Material>Grünabfall shreddern [h]</Material>
<Nettopreis>60</Nettopreis>
<Mwst>0.19</Mwst>
<Einheit>t</Einheit>
</tblMaterialarten>
<tblMaterialarten>
